<a href="https://colab.research.google.com/github/swimbeginner/TensorFlow2/blob/main/Numpy_quickReview_12192020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#basic declaration

In [3]:
one_dimensional_array=np.array([1, 2, 3, 4])
print(one_dimensional_array.shape)

(4,)


In [14]:
two_dimensional_array=np.array([[1,2],[3,4],[5,6]])
print(two_dimensional_array,'\n', two_dimensional_array.shape, two_dimensional_array[:,1:2].shape)
a=two_dimensional_array[:,1]
b=two_dimensional_array[:,0:2]
print(a,'\n',b)

[[1 2]
 [3 4]
 [5 6]] 
 (3, 2) (3, 1)
[2 4 6] 
 [[1 2]
 [3 4]
 [5 6]]


In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

#basic random numbers

In [25]:
random_integers_50_100=np.random.randint(low=50, high=100, size=(6))
print(random_integers_50_100)

[83 68 81 77 95 65]


In [28]:
random_floats=np.random.random([6])
random_floats

array([0.20401117, 0.97226496, 0.4920054 , 0.66964064, 0.8517382 ,
       0.86152943])

In [32]:
features=np.arange(6,21,dtype=int)
features
label = 3*features+4   # write your code here
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
